### PR TITLE
Update to use recommended issue template

### PR DESCRIPTION
**Pull request by gep13**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions - Not Required
- [x] Examples have been added for any significant new features - Not Required
- [x] README has been updated, if necessary - Not Required

### Motivation, issues

When viewing the current issue template on GitHub, you are presented with this information:

image

The documentation for this GitHub feature can be found here:

https://help.github.com/en/articles/about-issue-and-pull-request-templates

On reading that article, the recommendation is to switch to the new issue template format:

> It is possible to manually create a single issue template in Markdown using the legacy issue template workflow, and project contributors will automatically see the template's contents in the issue body. However, we recommend using the upgraded multiple issue template builder to create issue templates.

### Description

Remove the existing ISSUE_TEMPLATE.md file, and replace it with a new bug.md file in the ISSUE_TEMPLATE folder.

This opens up the potential for creating multiple issue templates, for example, one specifically for requesting a new feature, reporting a security finding, etc.

### Related Pull Requests

I have opened similar PR's in other Orb Repositories:

https://github.com/CircleCI-Public/twilio-orb/pull/3
https://github.com/CircleCI-Public/slack-orb/pull/88
https://github.com/CircleCI-Public/docker-orb/pull/23
https://github.com/CircleCI-Public/circleci-cli-orb/pull/2
https://github.com/CircleCI-Public/build-tools-orb/pull/15
https://github.com/CircleCI-Public/azure-cli-orb/pull/4

### CODE REVIEW

**Comment by eddiewebb** [comment]
@gep13 - in your research did it emerge what other types are available, and how a user would choose?

**Comment by eddiewebb** [comment]
FOund it https://help.github.com/en/articles/about-issue-and-pull-request-templates

I'd love to include either feature or generic template to make this change more complete.  I am thinking about features, and what we would want to know:

- Is this request related to exposing underlying capabilities of the tool?
- is this .... related to a version change
- a sample use case/scenarios that would leverage this feature

@CircleCI-Public/cpeng - any other ideas on what a feature report should include?

**Comment by gep13** [comment]
@eddiewebb you can absolutely go nuts and create as many as you like 😄 

Have a look at the following example:

https://github.com/babel/babel/issues/new/choose

image

NOTE:  The final one in the example above comes from having a `security.md` in the .github folder, also mentioned in the linked documentation.

I only included what is already in the repository, as I wasn't sure what other ones you would want/need as a project.  Having moved to the `ISSUE_TEMPLATE` folder, you can create as many as you like.

**Comment by gep13** [comment]
Apologies, I included a link to the documentation in my commit message, but I should have also included it in the PR comment.

**Comment by gep13** [comment]
@eddiewebb I would be happy to include additional templates in this PR, but I would need some input from yourself, and the team, to know what exactly is required.

**Comment by KyleTryon** [comment]
This is much appreciated thank you! We will need to update the issue templates in the orb starter kit as well for future orbs: https://github.com/CircleCI-Public/orb-starter-kit/tree/master/.github

**Comment by gep13** [comment]
@KyleTryon Ah, I didn't realise that there was a starter kit.  If someone doesn't get to this before me, I can make a PR into that repository as well.  I have opened a number of other PR's for some repositories making the same suggested change.  Thanks for merging this!

**Pull request merged**
